import type { Recursive } from "../utils";
import type { Token } from "./token";
import type { CompositionStyleObject } from "./style";

export type TextStyleProperty =
  | "color"
  | "direction"
  | "font"
  | "fontFamily"
  | "fontFeatureSettings"
  | "fontKerning"
  | "fontLanguageOverride"
  | "fontOpticalSizing"
  | "fontPalette"
  | "fontSize"
  | "fontSizeAdjust"
  | "fontStretch"
  | "fontStyle"
  | "fontSynthesis"
  | "fontVariant"
  | "fontVariantAlternates"
  | "fontVariantCaps"
  | "fontVariantLigatures"
  | "fontVariantNumeric"
  | "fontVariantPosition"
  | "fontVariationSettings"
  | "fontWeight"
  | "hangingPunctuation"
  | "hypens"
  | "hyphenateCharacter"
  | "hyphenateLimitChars"
  | "letterSpacing"
  | "lineBreak"
  | "lineHeight"
  | "quotes"
  | "overflowWrap"
  | "tabSize"
  | "textAlign"
  | "textAlignLast"
  | "textBox"
  | "textBoxEdge"
  | "textBoxTrim"
  | "textCombineUpright"
  | "textDecoration"
  | "textDecorationColor"
  | "textDecorationLine"
  | "textDecorationSkip"
  | "textDecorationSkipBox"
  | "textDecorationSkipInk"
  | "textDecorationSkipInset"
  | "textDecorationStyle"
  | "textDecorationThickness"
  | "textEmphasis"
  | "textEmphasisColor"
  | "textEmphasisPosition"
  | "textEmphasisStyle"
  | "textIndent"
  | "textJustify"
  | "textOrientation"
  | "textOverflow"
  | "textRendering"
  | "textShadow"
  | "textStroke"
  | "textStrokeColor"
  | "textStrokeWidth"
  | "textTransform"
  | "textUnderlineOffset"
  | "textUnderlinePosition"
  | "textWrap"
  | "textWrapMode"
  | "textWrapStyle"
  | "unicodeBidi"
  | "verticalAlign"
  | "whiteSpace"
  | "wordBreak"
  | "wordSpacing"
  | "writingMode";

export type TextStyle = CompositionStyleObject<TextStyleProperty>;
export type TextStyles = Recursive<Token<TextStyle>>;
