export const propertyCategoryMap: Record<string, string> = {
  margin: "spacing",
  marginTop: "spacing",
  marginRight: "spacing",
  marginBottom: "spacing",
  marginLeft: "spacing",
  marginX: "spacing",
  marginY: "spacing",
  padding: "spacing",
  paddingTop: "spacing",
  paddingRight: "spacing",
  paddingBottom: "spacing",
  paddingLeft: "spacing",
  paddingX: "spacing",
  paddingY: "spacing",
  gap: "spacing",
  rowGap: "spacing",
  columnGap: "spacing",
  top: "spacing",
  right: "spacing",
  bottom: "spacing",
  left: "spacing",

  width: "sizes",
  height: "sizes",
  minWidth: "sizes",
  maxWidth: "sizes",
  minHeight: "sizes",
  maxHeight: "sizes",
  flexBasis: "sizes",

  color: "colors",
  backgroundColor: "colors",
  borderColor: "colors",
  borderTopColor: "colors",
  borderRightColor: "colors",
  borderBottomColor: "colors",
  borderLeftColor: "colors",
  caretColor: "colors",
  columnRuleColor: "colors",
  outlineColor: "colors",
  textDecorationColor: "colors",
  fill: "colors",
  stroke: "colors",

  fontSize: "fontSizes",
  fontWeight: "fontWeights",
  fontFamily: "fonts",
  lineHeight: "lineHeights",
  letterSpacing: "letterSpacings",

  borderRadius: "radii",
  borderTopLeftRadius: "radii",
  borderTopRightRadius: "radii",
  borderBottomLeftRadius: "radii",
  borderBottomRightRadius: "radii",
  borderTopRadius: "radii",
  borderRightRadius: "radii",
  borderBottomRadius: "radii",
  borderLeftRadius: "radii",

  borderWidth: "borderWidths",
  borderTopWidth: "borderWidths",
  borderRightWidth: "borderWidths",
  borderBottomWidth: "borderWidths",
  borderLeftWidth: "borderWidths",

  border: "borders",
  borderTop: "borders",
  borderRight: "borders",
  borderBottom: "borders",
  borderLeft: "borders",

  boxShadow: "shadows",
  opacity: "opacity",
  zIndex: "zIndex",
  cursor: "cursor",

  animation: "animations",
  animationDuration: "durations",
  animationTimingFunction: "easings",
};
